export const FETCH_BOOK = 'FETCH_BOOK'

export const FETCH_BOOKS_BEGIN = 'FETCH_BOOKS_BEGIN'
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE'

export const BOOK_SELECTED = 'BOOK_SELECTED'