export const fetchBookActions = {
    FETCH_BOOK: 'FETCH_BOOK',
    FETCH_BOOKS_BEGIN: 'FETCH_BOOKS_BEGIN',
    FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
    FETCH_BOOKS_FAILURE: 'FETCH_BOOKS_FAILURE',
}

export const postBookActions = {
    POST_BOOK: 'POST_BOOK',
    POST_BOOK_BEGIN: 'POST_BOOK_BEGIN',
    POST_BOOK_SUCCESS: 'POST_BOOK_SUCCESS',
    POST_BOOK_FAILURE: 'POST_BOOK_FAILURE',
}

export const likeBookActions = {
    LIKE_BOOK: 'LIKE_BOOK',
    LIKE_BOOK_BEGIN: 'LIKE_BOOK_BEGIN',
    LIKE_BOOK_SUCCESS: 'LIKE_BOOK_SUCCESS',
    LIKE_BOOK_FAILURE: 'LIKE_BOOK_FAILURE',
}
export const viewBookActions = {
    VIEW_BOOK: 'VIEW_BOOK',
    VIEW_BOOK_BEGIN: 'VIEW_BOOK_BEGIN',
    VIEW_BOOK_SUCCESS: 'VIEW_BOOK_SUCCESS',
    VIEW_BOOK_FAILURE: 'VIEW_BOOK_FAILURE',
}

export const fetchUserBookActions = {
    FETCH_USER_BOOK: 'FETCH_USER_BOOK',
    FETCH_USER_BOOKS_BEGIN: 'FETCH_USER_BOOKS_BEGIN',
    FETCH_USER_BOOKS_SUCCESS: 'FETCH_USER_BOOKS_SUCCESS',
    FETCH_USER_BOOKS_FAILURE: 'FETCH_USER_BOOKS_FAILURE',
}

export const readStateActions = {
    READ_STATE: 'READ_STATE',
    READ_STATE_TOREAD: 'READ_STATE_TOREAD',
    READ_STATE_READING: 'READ_STATE_READING',
    READ_STATE_READ: 'READ_STATE_READ'
}

export const updateBookActions = {
    PATCH_USER_BOOK: 'PATCH_USER_BOOK',
    PATCH_USER_BOOK_BEGIN: 'PATCH_USER_BOOK_BEGIN',
    PATCH_USER_BOOK_SUCCESS: 'PATCH_USER_BOOK_SUCCESS',
    PATCH_USER_BOOK_FAILURE: 'PATCH_USER_BOOK_FAILURE',
}


export const deleteBookActions = {
    DELETE_BOOK: 'DELETE_BOOK',
    DELETE_BOOK_BEGIN: 'DELETE_BOOK_BEGIN',
    DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_FAILURE: 'DELETE_BOOK_FAILURE',
}

export const selectBookActions = {
    SELECT_NEW_BOOK: 'SELECT_NEW_BOOK',
    SELECT_USER_BOOK: 'SELECT_USER_BOOK'
}
