export const fetchBookActions = {
    FETCH_BOOK: 'FETCH_BOOK',
    FETCH_BOOKS_BEGIN: 'FETCH_BOOKS_BEGIN',
    FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
    FETCH_BOOKS_FAILURE: 'FETCH_BOOKS_FAILURE',
}

export const postBookActions = {
    POST_BOOK: 'POST_BOOK',
    POST_BOOK_BEGIN: 'POST_BOOK_BEGIN',
    POST_BOOK_SUCCESS: 'POST_BOOK_SUCCESS',
    POST_BOOK_FAILURE: 'POST_BOOK_FAILURE',
}

export const BOOK_SELECTED = 'BOOK_SELECTED'

export const BOOK_ADDED = 'BOOK_ADDED'